if(CPP_COMMONS_ENABLE_SANITIZERS)
    message(STATUS "Sanitizers enabled: ${CPP_COMMONS_ENABLE_SANITIZERS}")
    if(CPP_COMMONS_ENABLE_SANITIZERS STREQUAL "address")
        add_compile_options(-fsanitize=address,undefined -fno-omit-frame-pointer)
        add_link_options(-fsanitize=address,undefined)
    elseif(CPP_COMMONS_ENABLE_SANITIZERS STREQUAL "thread")
        add_compile_options(-fsanitize=thread)
        add_link_options(-fsanitize=thread)
    elseif(CPP_COMMONS_ENABLE_SANITIZERS STREQUAL "memory")
        add_compile_options(-fsanitize=memory -fno-omit-frame-pointer)
        add_link_options(-fsanitize=memory)
    endif()
endif()
